# Generated by Django 5.0.3 on 2024-05-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrustCareMedicalGroup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
