# Generated by Django 5.0.3 on 2024-06-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrustCareMedicalGroup', '0002_doctor_password_patient_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='state',
        ),
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
