# Generated by Django 5.0.3 on 2024-06-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrustCareMedicalGroup', '0003_remove_doctor_address_remove_doctor_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.CharField(default='false', max_length=50),
        ),
    ]
